version: '3'
services:
  eureka-node:
    image: eureka-node
    build: ./eureka-node
    container_name: eureka-node
    ports:
      - '8761:8761'
    networks:
      - vertx-network
  postgres-node:
    image: postgres-node
    build: ./postgres-node
    container_name: postgres-node
    ports:
      - '5432:5432'
    networks:
      - vertx-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: socnet
      POSTGRES_DB: socnet
  vertx-node:
    image: vertx-node
    build: ./vertx-node
    container_name: vertx-node
    links:
      - postgres-node
      - eureka-node
    ports:
      - '8585:8585'
    networks:
      - vertx-network
networks:
  vertx-network:
    driver: overlay
