version: '2'
services:
  eureka-node:
    image: eureka-node
    build: ./eureka-node
    container_name: "eureka-node"      
    ports:
      - "8761:8761"     
    networks:
      - overlay
  postgres-node:
    image: postgres-node
    build: ./postgres-node
    container_name: "postgres-node" 
    ports:
     - "5432:5432"  
    networks:
     - overlay     
    environment:     
      POSTGRES_USER: "socnet"
      POSTGRES_PASSWORD: "socnet"
      POSTGRES_DB: "socnet"      
  vertx-node:
    image: vertx-node
    build: ./vertx-node
    container_name: "vertx-node"
    links:        
      - eureka-node  
      - postgres-node     
    ports:
      - "8080:8080"
    networks:
      - overlay

networks:
  overlay:      
 