version: "3.1"
services:
  postgres-node:
    image: postgres-node
    build: ./postgres-node
    container_name: "postgres-node" 
    ports:
     - "5432:5432"  
    networks:
     - vertx-network     
    environment:     
      POSTGRES_USER: "socnet"
      POSTGRES_PASSWORD: "socnet"
      POSTGRES_DB: "socnet"      
  vertx-node:
    image: vertx-node
    build: ./vertx-node
    container_name: "vertx-node"
    links:   
      - postgres-node     
    ports:
      - "8080:8080"
    networks:
      - vertx-network
networks:
  vertx-network:
    driver: overlay