#server:
#  port: 8080

management:
  security:  
    enabled: false 
    
spring:
  application:
    name: vertxnode
    profiles:
    active:
      default   
  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: none
        dialect:  org.hibernate.dialect.MySQLDialect
  datasource:
        url: jdbc:mysql://192.168.99.100:3306/airlines?zeroDateTimeBehavior=convertToNull&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        username: admin
        password: root
        driver-class-name: com.mysql.jdbc.Driver        

    
hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000        
