spring:
  application:
    name: vertxnode
    profiles:
    active:
      default   
  jpa:
      database: postgresql
      hibernate:
        ddl-auto: none
        ##dialect:  org.hibernate.dialect.MySQLDialect
        dialect:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
        ##url: jdbc:mysql://mysql-node:3306/airlines?zeroDateTimeBehavior=convertToNull&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        url: jdbc:mysql://192.168.99.100:5432/socnet
        username: armdev
        password: armdev
        ##driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: org.postgresql.Driver
        
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-node:8761/eureka}
        